{{ config(materialized='table') }}

-- jira_issues

select  stylingcontractorhsp as styling_contractor_hsp,
        keyhandoverdate as key_hand_over_date,
        propertystate as property_state,
        created as created,
        statuscategory as status_category,
        development as development,
        reporter as reporter,
        constant1 as constant_1,
        originalestimatehrs as original_estimated_hours,
        timespenthrs as time_spent_hours,
        priority as priority,
        originalestimateinclsubtaskshrs as original_estimate_including_subtasks_hours,
        bathrooms as bathrooms,
        -- Check if this is the same across the board.
        reservation as reservation_code,
        dateofkeyhandover as date_of_key_handover,
        clientname as client_name,
        referralpartner as referral_partner,
        jiraissueid as jira_issue_id,
        datecontractsigned as date_contract_signed,
        apicallid as api_call_id,
        key as key,
        datepaymentreceived as date_payment_received,
        clientemailaddress as client_email,
        modifieddate as modified_date,
        keypickupdetails as key_pick_up_details,
        projectlead as project_lead,
        andchilloverheadscosts as and_chill_overhead_costs,
        -- Cast this as ddmmyy
        parse_date('%m%d%Y', created_mmddyyyy) as created_date_1,
        bedrooms as bedrooms,
        typicalcost as typical_cost,
        `rank` as `rank`,
        case when LENGTH(bookingautomationid) != 5 then null
        else cast(bookingautomationid as int64) end as ba_id_code,
        summary as summary,
        linkedissues as linked_issues,
        lastviewed as last_viewed,
        creator as creator,
        watchers as watchers,
        created_2 as created_2,
        furnitureremovalduedate as furniture_removal_date,
        projecttype as project_type,
        _sdc_table_version as sdc_table_version,
        parentissuestatus as parent_issue_status,
        remainingestimatehrs as remaining_estimate_hours,
        referralpartnercommission as referral_partner_commission,
        datepropertylisted as date_property_listed,
        workratio as work_ratio,
        typeofissue as type_of_issue,
        chartdateoffirstresponse as chart_date_of_first_response,
        dateofphotography as photography_date,
        parentissuesummary as parent_issues_summary,
        propertylistingdate as property_listing_date,
        bdmcommission as bdm_commission,
        projectcategory as project_category,
        propertysettlementdate as property_settlement_date,
        status as status,
        subtasks as subtasks,
        propertyaddress as property_address,
        timespentinclsubtaskshrs as time_spent_including_subtasks_hours,
        datehomesetupfeepaid as date_home_setup_fee_paid,
        propertyparkinglocation as property_parking_location,
        furnitureproductexpenses as furniture_product_expenses,
        _sdc_received_at as sdc_received_at,
        _sdc_sequence as sdc_sequence,
        hostfullyurl as hostfully_url,
        datepropertyavailable as date_property_available,
        assignee as ppe,
        endofleasecleanduedate as end_of_lease_clean_due_date,
        dateofinteriorfitout as date_of_interior_fit_out,
        projectdescription as project_description,
        parentissuepriority as parent_issue_priority,
        duedate as due_date,
        propertymanagementcommission as property_management_commission,
        updated as updated,
        projectname as project_name,
        charttimeinstatus as chart_time_in_status,
        projectkey as project_key,
        propertymanagementcommissiontype as property_management_commission_type,
        parentissuetype as parent_issue_type,
        parentissuekey as parent_issue_key,
        homesetupfee as home_setup_fee,
        _sdc_batched_at as sdc_batched_at,
        issuetype as issue_type,
        attachmentnames as attachment_names,
        createddate as created_date,
        remainingestimateinclsubtaskshrs as remaining_estimate_including_subtasks_hours,
        propertyupcomingcheckouts as property_upcoming_check_outs,
        description as description,
        paymentterms as payment_terms,
        transfertohomestyling as transfer_to_home_styling,
        resolved as resolved,
        resolution as resolution
        from `and-chill-database.sql_server.JiraIssues`
