{{ config(materialized='view') }}

-- Taking raw data from Jira Issues.

SELECT  projecttype AS project_type,
        key AS key,
        jiraissueid AS jira_issue_id,
        created AS created,
        statuscategory AS status_category,
        reporter AS reporter,
        priority AS priority,
        CASE  WHEN LENGTH(bookingautomationid) != 5 THEN NULL
                      ELSE CAST(bookingautomationid as INT64)
                      END AS ba_id_code,
        propertyaddress AS property_address,
        datecontractsigned AS date_contract_signed,
        bedrooms AS bedrooms,
        bathrooms AS bathrooms,
        reservation AS reservation_code,
        -- What's the difference between these two fields
        keyhandoverdate AS key_hand_over_date,
        dateofkeyhandover AS date_of_key_handover,
        clientname AS client_name,
        referralpartner AS referral_partner,
        jiraissueid AS jira_issue_id,
        key AS key,
        datepaymentreceived AS date_payment_received,
        clientemailaddress AS client_email,
        modifieddate AS modified_date,
        keypickupdetails AS key_pick_up_details,
        projectlead AS project_lead,
        andchilloverheadscosts AS and_chill_overhead_costs,
        -- Cast this as ddmmyy
        PARSE_DATE('%m%d%Y', created_mmddyyyy) AS created_date_1,
        typicalcost AS typical_cost,
        `rank` AS `rank`,
        summary AS summary,
        linkedissues AS linked_issues,
        lastviewed AS last_viewed,
        creator AS creator,
        created_2 AS created_2,
        furnitureremovalduedate AS furniture_removal_date,
        parentissuestatus AS parent_issue_status,
        remainingestimatehrs AS remaining_estimate_hours,
        referralpartnercommission AS referral_partner_commission,
        datepropertylisted AS date_property_listed,
        workratio AS work_ratio,
        typeofissue AS type_of_issue,
        chartdateoffirstresponse AS chart_date_of_first_response,
        dateofphotography AS photography_date,
        parentissuesummary AS parent_issues_summary,
        propertylistingdate AS property_listing_date,
        bdmcommission AS bdm_commission,
        projectcategory AS project_category,
        propertysettlementdate AS property_settlement_date,
        status AS status,
        propertyaddress AS property_address,
        furnitureproductexpenses AS furniture_product_expenses,
        datepropertyavailable AS date_property_available,
        assignee AS ppe,
        projectdescription AS project_description,
        parentissuepriority AS parent_issue_priority,
        propertymanagementcommission AS property_management_commission,
        projectname AS project_name,
        charttimeinstatus AS chart_time_in_status,
        projectkey AS project_key,
        propertymanagementcommissiontype AS property_management_commission_type,
        parentissuetype AS parent_issue_type,
        parentissuekey AS parent_issue_key,
        homesetupfee AS home_setup_fee,
        issuetype AS issue_type,
        attachmentnames AS attachment_names,
        createddate AS created_date,
        description AS description,
        paymentterms AS payment_terms,
        resolved AS resolved,
        resolution AS resolution
FROM `and-chill-database.sql_server.JiraIssues`
